### ISSUE TITLE
MainActivity에 @AndroidEntryPoint 어노테이션 달아주세요

### ISSUE THREAD

**Issue by shw0471** [It-s-okay-if-you-want/DongGeulMongGeul-Android#2]
https://github.com/It-s-okay-if-you-want/DongGeulMongGeul-Android/blob/996b924fb0c7a99b85956cbcb2605fa06c026c2b/app/src/main/java/com/okifwant/donggeulmonggeul_android/ui/MainActivity.kt?_pjax=%23repo-content-pjax-container#L11

- [ ] 달기

**Comment by minjun8946** [comment]
thank you!!

**Comment by ParkSangSun1** [comment]
추가했습니다! 이슈를 닫겠습니다
